spring.application.name=Yara

# ===============================
# DATABASE
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/yaradb
spring.datasource.username=postgres
spring.datasource.password=admin

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.time-zone=America/Lima
spring.jpa.properties.hibernate.jdbc.time_zone=America/Lima